### ISSUE TITLE
want to add translation folder

### ISSUE THREAD

**Issue by iamrahulmahato** [metacall/jupyter-kernel#179]
## 📚 Documentation

Want to add a translation folder so that who are not native of English they could Jupiter Kernel  to specific i want to add Hindi translation

I am a participant of open force 2022

**Comment by iamrahulmahato** [comment]
@giarve The PR is made #180  . Kindly review and merge it.
Thank You

**Comment by HarshCasper** [comment]
Hi @iamrahulmahato 

Currently, we are looking for more features, bug fixes and enhancements. Translations are not a priority right now. Thanks!
